version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: michaupop
      POSTGRES_PASSWORD: Pokemony12
      POSTGRES_DB: cinemascraper
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: