CREATE TABLE IF NOT EXISTS films (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cinema VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    UNIQUE (cinema, title)
    );

CREATE TABLE IF NOT EXISTS showtimes (
id INT AUTO_INCREMENT PRIMARY KEY,
film_id INT NOT NULL,
show_datetime DATETIME NOT NULL,
FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE
    );
